### ISSUE TITLE
alpha broken?

### ISSUE THREAD

**Issue by aztecsensei** [Maujoe/godot-simple-wind-shader#1]
hello! im using ur shader but it looks like its broken, can u add alpha scissor please, 
thanks.
here look:
![2019-02-02_132315](https://user-images.githubusercontent.com/33324484/52168343-c3c43b00-26ee-11e9-8067-0a6f7019e760.jpg)

**Comment by Maujoe** [comment]
From the picture it's looks like that the flower texture has some transparent spots that could be fixed via photo editing. 

But alpha scissor is a nice feature. I have created a second shader variant with alpha scissor option.
(With Godot 3.1 this kind of customizations will become user friendlier because of the visual shader editor :) )

**Comment by aztecsensei** [comment]
thanks works but the collision doesnt move with the mesh??
im gonna share it with the community soon if u wanna play around with it.
cheers.
![2019-02-10_140910](https://user-images.githubusercontent.com/33324484/52538885-84749a80-2d3d-11e9-95b4-5087df171274.jpg)

**Comment by Maujoe** [comment]
This is correct and the usual behavior because the shaders only compute the visual part not the collision, so the collision of the physics engine behaves still the same. But usually most plants have no collision or it is faked via shader.
